- name: demo on inventory variabless
  hosts: frontend
  connection: frontend
  tasks:
  - name: print information
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"