- name: demo on inventory variabless
  hosts: localhost
  connection: localhost
  tasks:
  - name: print information
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"