- name: demo on inventory variables
  hosts: frontend
  vars:
    COURSE: "AWS with DevOps"
  tasks:
    - name: print information
      debug:
        msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}" ,common_key: {{ common_key }} 