[local]
   #localhost
   172.31.39.138 ansible_user=ec2-user
   172.31.13.77 ansible_user=ec2-user
   172.31.7.26 ansible_user=ec2-user
[local:vars]
  COURSE="Ansible"
  TRAINER="MN"
  DURATION="150HRS"
