[frontend]
172.31.7.26

[local]
localhost

;local group vars
;[local:vars]
;COURSE: "Ansible"
;TRAINER: "MN"
;DURATION: "150HRS"

; [frontend:vars]
; COURSE="Ansible"
; TRAINER="Sivakumar"
; DURATION="10HRS"