#[frontend]
  #172.31.7.26 COURSE="Ansible for node-1"
  #172.31.39.138 COURSE="Ansible for node-2"


[local]
  localhost
      172.31.7.26 COURSE="Ansible for node-1"
      1172.31.39.138 COURSE="Ansible for node-2"

[local:vars]
  COURSE="Ansible"
  TRAINER="MN"
  DURATION="150HRS"

  #[frontend:vars]
  #COURSE="Ansible"
  #TRAINER="MBB"
  #DURATION="150HRS"
